# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb9ce46c820a634c7d2f739329bdf389578b7b6ad5a49c74661cf5a3f33fce850750bc39ab2dc39a0af1add6ac367f930c7c752ccecbe7dd595f2ec351e39e77

test:
  secret_key_base: 486d9c7f41d9328a9b7e4a5679a7b1eb4e3a939d729ca36a8be46dca8e25f399517a22c2a722779b74876cadc6cf3b2a02c6de2464813da86524e85110437a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
